name: glsegenv2
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - pip==24.2
  - python==3.12.5
  - pip:
      - torch==2.4.1
      - torchvision==0.19.1
      - segmentation-models-pytorch==0.3.4
      - pytorch-lightning==2.4.0
      - tensorboard==2.17.1
      - torchmetrics==1.4.2
      - pandas==2.2.2
      - geopandas==1.0.1
      - xarray==2024.9.0
      - rioxarray==0.17.0
      - h5netcdf==1.3.0
      - netCDF4==1.7.1.post2
      - tqdm==4.66.5
      - matplotlib==3.9.2
      - opencv-python==4.10.0.84
      - protobuf==5.28.1
      - pyproj==3.6.1
      - scikit-learn==1.5.2
      - numpy==1.26.4
      - oggm==1.6.2
      - xdem==0.0.20
      - salem==0.3.11