config: 'S2_ALPS_PLUS'  # class name from configs.py based on which remaining data parameters are set in main_train.py

data:
  split: 'split_1'
  minmax_scale_data: False
  standardize_data: True
  scale_each_band: True
  train_batch_size: 16
  val_batch_size: 32
  test_batch_size: 32
  num_workers: 16
  use_augmentation: False

task:
  seed: 1
  loss: 'focal'
  optimization:
    optimizer:
      - name: 'Adam'
        args:
          lr: 0.0001
    lr_schedule: null

logger:
  save_dir: '../data/external/_experiments/s2_alps_plus'
  name: 'unet/split_1'

trainer:
  devices: [ 0 ]
  accelerator: 'gpu'
  log_every_n_steps: 10
  max_epochs: 30
  deterministic: True

model:
  class: 'SegModelSMP'
  name: 'Unet'
  inputs:
    bands_input: [ 'R', 'G', 'B', 'NIR', 'SWIR' ]
    band_mask: 'mask_nok'
    dem: True
    dhdt: True
    optical_indices: ['NDVI', 'NDWI', 'NDSI']
    dem_features: [ 'slope', 'aspect_sin', 'aspect_cos', 'planform_curvature', 'profile_curvature', 'terrain_ruggedness_index' ]
    velocity: False
  args:
    encoder_name: 'resnet34'
    encoder_weights: 'imagenet'
    encoder_depth: 5
    activation: 'sigmoid'
    decoder_use_batchnorm: False
    decoder_attention_type: null