data:
  data_root_dir: '../data/external/wd/patches_orig_r_64_s_32/split_1'
  train_dir_name: 'fold_train/event'
  val_dir_name: 'fold_valid'
  test_dir_name: 'fold_test'
  rasters_dir: '../data/s2_data/rasters'
  minmax_scale_data: False
  standardize_data: False
  scale_each_band: True
  data_stats_fp: null
  train_batch_size: 32
  val_batch_size: 256
  test_batch_size: 256
  num_workers: 16

task:
  seed: 42
  loss:
    name: 'MaskedDist'
    args: {
      distance_type: 'BCE'
    }
  optimization:
    optimizer:
      - name: 'SGD'
        args:
          lr: 0.01
          nesterov: True
          momentum: 0.9
    lr_schedule: null

logger:
  save_dir: '../data/external/experiments_server'
  name: 'unet/cv/split_1'

trainer:
  devices: [ 0 ]
  accelerator: 'gpu'
#  limit_train_batches: 8
#  limit_val_batches: 4
  log_every_n_steps: 10
  max_epochs: 50
  deterministic: True

model:
  class: 'SegModel'
  name: 'Unet'
  inputs:
    elevation: True
  args:
    encoder_name: 'resnet34'
    encoder_weights: 'imagenet'
    encoder_depth: 5
    activation: 'sigmoid'
    decoder_use_batchnorm: False
    decoder_attention_type: null