data:
  data_root_dir: '../data/external/wd/s2_alps_plus/inv/patches/r_128_s_64/'
  all_splits_fp: '../data/external/wd/s2_alps_plus/cv_split_outlines/map_all_splits_all_folds.csv'
  split: "split_1"
  rasters_dir: '../data/external/wd/s2_alps_plus/inv/glacier_wide'
  minmax_scale_data: False
  standardize_data: True
  scale_each_band: True
  data_stats_fp: '../data/external/wd/s2_alps_plus/inv/aux_data/norm_stats/r_128_s_64/split_1/stats_train_patches_agg.csv'
  train_batch_size: 16
  val_batch_size: 32
  test_batch_size: 32
  num_workers: 16
  use_augmentation: False

task:
  seed: 1
  loss: 'focal'
  optimization:
    optimizer:
      - name: 'Adam'
        args:
          lr: 0.0001
    lr_schedule: null

logger:
  save_dir: '../data/external/_experiments/s2_alps_plus'
  name: 'unet/split_1'

trainer:
  devices: [ 0 ]
  accelerator: 'gpu'
#  limit_train_batches: 8
#  limit_val_batches: 4
  log_every_n_steps: 10
  max_epochs: 30
  deterministic: True

model:
  class: 'SegModel'
  name: 'Unet'
  inputs:
    bands_input: [ 'B4', 'B3', 'B2', 'B8', 'B11']
    bands_mask: [ '~FILL_MASK', '~CLOUDLESS_MASK']
    dem: True
    dhdt: True
    optical_indices: True
    dem_features: True
    velocity: False
  args:
#    encoder_name: 'resnet50'
    encoder_name: 'resnet34'
    encoder_weights: 'imagenet'
#    encoder_weights: null
    encoder_depth: 5
    activation: 'sigmoid'
    decoder_use_batchnorm: False
    decoder_attention_type: null
  other:
    external_encoder_weights: null
#    external_encoder_weights: '../data/external/pretraining/B13_rn50_moco_0099.pth'